name: Whats next
favicon: null
layout_spectrum: 0.8389193292241544
typography_spectrum: 0.5221429574303329
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ecf1ff'
    - '#aebfd5'
    - '#090909'
    - '#49433f'
    - '#5f808b'
  brandStrength: 0.1875
  lightness: 0.6579877564217895
  saturation: 0.24903757078573108
  rhythmicContrast: 0.5
purpose: []
